blank_issues_enabled: false

contact_links:
  - name: Discussions
    url: https://github.com/CStaks/template/discussions
    about: Ask questions or propose ideas that are not bugs or features.

  - name: Contact Us
    url: https://cstaks.github.io/contact.html
    about: For any questions/issues, you can contact us here.
